amcl:
  ros__parameters:
    use_sim_time: true
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_footprint"
    beam_skip_distance: 0.5
    do_beamskip: true
    global_frame_id: "map"
    laser_max_range: 12.0
    laser_min_range: 0.1
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 3000
    min_particles: 500
    odom_frame_id: "odom"
    update_min_a: 0.2
    update_min_d: 0.25
    resample_interval: 1
    transform_tolerance: 1.0

map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: config/map_1749886992.yaml  # Adjust if necessary

bt_navigator:
  ros__parameters:
    use_sim_time: true
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
    global_frame: "map"
    robot_base_frame: "base_footprint"
    odom_topic: "odom"
    transform_tolerance: 0.5

planner_server:
  ros__parameters:
    use_sim_time: true
    expected_planner_frequency: 10.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      critics: ["RotateToGoal", "PathAlign", "GoalAlign", "ObstacleFootprintCritic", "PreferForwardCritic"]

      RotateToGoal:
        enabled: true
      PathAlign:
        enabled: true
      GoalAlign:
        enabled: true
      ObstacleFootprintCritic:
        enabled: true
      PreferForwardCritic:
        enabled: true

behavior_server:
  ros__parameters:
    use_sim_time: true

waypoint_follower:
  ros__parameters:
    use_sim_time: true

velocity_smoother:
  ros__parameters:
    use_sim_time: true

collision_monitor:
  ros__parameters:
    use_sim_time: true

lifecycle_manager:
  ros__parameters:
    use_sim_time: true
    autostart: true
    node_names: [
      "map_server",
      "amcl",
      "planner_server",
      "controller_server",
      "bt_navigator",
      "behavior_server",
      "waypoint_follower",
      "velocity_smoother",
      "collision_monitor"
    ]